
import ReduxProvider from "./redux/ReduxProvider";

import "./globals.css";

export const metadata = {
  title: "Ecommerce Dashboard",
  description: "Generated by Nipol Roy",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
